In [1]:
import numpy as np

In [2]:
def getSequences():
    print("enter first sequence")
    seq1 = input()
    print("enter second sequence")
    seq2 = input()
    return seq1, seq2

In [3]:
def NWAlgorithm(seq1, seq2, match, mismatch, gap):
#     initialize array with 0s
    result=np.zeros((len(seq1)+1,len(seq2)+1))
#     calculate the initial cumulative gaps
    for i in range(len(seq1)+1):
        result[i][0]=i*gap
    for j in range(len(seq2)+1):
        result[0][j]=j*gap
#     calculate maximum score for each cell
    for i in range(1,len(seq1)+1):
        for j in range(1,len(seq2)+1):
#             calculate the 3 possible values
            case1 = result[i-1][j-1] + (match if(seq1[i-1] == seq2[j-1]) else mismatch)
            case2 = result[i-1][j]+gap
            case3 = result[i][j-1]+gap
#             put the maximum
            result[i][j]=max(case1,case2,case3)
    print(result)
    return result

In [5]:
def getAlignment(matrix, seq1,seq2):
    alignmentSeq1=""
    alignmentSeq2=""
#     start from the last cell
    i=len(seq1)
    j=len(seq2)
    while (i >0 or j >0):
#         max neigbouring cell
        maxCell=max(matrix[i-1][j-1],matrix[i][j-1],matrix[i-1][j])
#     if there's a match or the diagonal neighbour cell is the maxCell
        if (seq1[i-1] == seq2[j-1] or maxCell == matrix[i-1][j-1]):
            alignmentSeq1=seq1[i-1] + alignmentSeq1
            alignmentSeq2=seq2[j-1] + alignmentSeq2
            i-=  1
            j-=  1
            
#         case of vertical gap (maxCell is the upper neighbour)
        elif (maxCell==matrix[i-1][j]):  
            alignmentSeq1=seq1[i-1] + alignmentSeq1
            alignmentSeq2="-" + alignmentSeq2
            i-=1
#         case of horizontal gaps
        else:
            alignmentSeq1="-" + alignmentSeq1
            alignmentSeq2=seq2[j-1] + alignmentSeq2
            j-= 1

    print(alignmentSeq1)
    print(alignmentSeq2)


In [6]:
# seq1 (vertical axis), seq2 (horizontal axis)
seq1, seq2 = getSequences()
print("matrix: ")
# match=1, mismatch = gap = -1
matrix = NWAlgorithm(seq1,seq2, 2, -1, -1)
print("alignment: ")
getAlignment(matrix,seq1,seq2)

enter first sequence
TTCATA
enter second sequence
TGCTCGTA
matrix: 
[[ 0. -1. -2. -3. -4. -5. -6. -7. -8.]
 [-1.  2.  1.  0. -1. -2. -3. -4. -5.]
 [-2.  1.  1.  0.  2.  1.  0. -1. -2.]
 [-3.  0.  0.  3.  2.  4.  3.  2.  1.]
 [-4. -1. -1.  2.  2.  3.  3.  2.  4.]
 [-5. -2. -2.  1.  4.  3.  2.  5.  4.]
 [-6. -3. -3.  0.  3.  3.  2.  4.  7.]]
alignment: 
T--TCATA
TGCTCGTA
