In [1]:
import numpy as np

In [2]:
def getSequences():
    print("enter first sequence")
    seq1 = input()
    print("enter second sequence")
    seq2 = input()
    return seq1, seq2

In [3]:
def SWAlgorithm(seq1, seq2, match, mismatch, gap):
#     initialize array with 0s
    result=np.zeros((len(seq1)+1,len(seq2)+1))
#     initial max score in the table
    maxScore=0
#     maxScore indices
    imax=0
    jmax=0
#     calculate maximum score for each cell
    for i in range(1,len(seq1)+1):
        for j in range(1,len(seq2)+1):
#             calculate the 3 possible values
            case1 = result[i-1][j-1] + (match if(seq1[i-1] == seq2[j-1]) else mismatch)
            case2 = result[i-1][j]+gap
            case3 = result[i][j-1]+gap
#             put the maximum
            result[i][j]=max(case1,case2,case3,0)
            if result[i][j] >= maxScore:
                imax = i
                jmax = j
                maxScore = result[i][j];
    print(result)
    return result, imax, jmax

In [4]:
def getAlignment(matrix, seq1,seq2, imax, jmax):
    alignmentSeq1=""
    alignmentSeq2=""
#     start from the maximum score cell
    i=imax
    j=jmax
    while ((i >0 or j >0) and matrix[i][j]!=0):
#         max neighbouring cell
        maxCell=max(matrix[i-1][j-1],matrix[i][j-1],matrix[i-1][j])
#     if there's a match or the diagonal neighbour cell is the maxCell
        if (seq1[i-1] == seq2[j-1] or maxCell == matrix[i-1][j-1]):
            alignmentSeq1=seq1[i-1] + alignmentSeq1
            alignmentSeq2=seq2[j-1] + alignmentSeq2
            i-=  1
            j-=  1
#         case of vertical gap (maxCell is the upper neighbour)
        elif (maxCell==matrix[i-1][j]):  
            alignmentSeq1=seq1[i-1] + alignmentSeq1
            alignmentSeq2="-" + alignmentSeq2
            i-=1
#         case of horizontal gap
        else:
            alignmentSeq1="-" + alignmentSeq1
            alignmentSeq2=seq2[j-1] + alignmentSeq2
            j-= 1

    print(alignmentSeq1)
    print(alignmentSeq2)

In [6]:
# seq1 (vertical axis), seq2 (horizontal axis)
seq1, seq2 = getSequences()
print("matrix:")
# match=3, mismatch = -3 gap = -2
matrix, imax, jmax = SWAlgorithm(seq1,seq2, 3, -3, -2)
print("Alignment:")
getAlignment(matrix,seq1, seq2, imax, jmax)

enter first sequence
GGTTGACTA
enter second sequence
TGTTACGG
matrix:
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  3.  1.  0.  0.  0.  3.  3.]
 [ 0.  0.  3.  1.  0.  0.  0.  3.  6.]
 [ 0.  3.  1.  6.  4.  2.  0.  1.  4.]
 [ 0.  3.  1.  4.  9.  7.  5.  3.  2.]
 [ 0.  1.  6.  4.  7.  6.  4.  8.  6.]
 [ 0.  0.  4.  3.  5. 10.  8.  6.  5.]
 [ 0.  0.  2.  1.  3.  8. 13. 11.  9.]
 [ 0.  3.  1.  5.  4.  6. 11. 10.  8.]
 [ 0.  1.  0.  3.  2.  7.  9.  8.  7.]]
Alignment:
GTTGAC
GTT-AC
